[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taskman"
version = "0.1.0"
description = "Simple project and task manager with CLI and UI."
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "Taskman Authors" }
]
dependencies = [
  "prettytable>=3.0",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
]

[project.scripts]
taskman-ui = "taskman.tasker_server:main"
taskman-cli = "taskman.cli.task_manager:main_cli"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
taskman = [
  "ui/*.html",
  "ui/*.css",
]
